acm-uga/openSourceSpring23

- README.md
Added name and discord to readme
> JasonWaryold-ReadMe

- README.md
This commit just adds my name & discord tag to the project readme. Excited for our meeting today!
> Add Jack Fletcher

- my-app/src/App.js
- my-app/src/components/LoginPage/LoginPage.css
- my-app/src/components/LoginPage/LoginPage.jsx
> Added forgot password and create new account options to login page

- backend/README.md
Add section to backend README.md showing easiest way to run it.
> Update backend README.md

- my-app/public/index.html
I didnt make an issue because it was a small change
> Changed the tab name on the website to "UGA Marketplace"

- my-app/src/components/CreateAccountPage/CreateAccountPage.jsx
There was an issue for checking if the number was valid. I fixed it so now it should be good
> Fixed Number Validation

- my-app/src/App.js
- my-app/src/components/FAQPage/FAQPage.css
- my-app/src/components/FAQPage/FAQPage.jsx
- my-app/src/components/HomeNavbar/HomeNavbar.jsx
Added the FAQ Page to the nav bar, along with css styling and containers to enter questions and answers
> Added the FAQ page with fillers

- .dockerignore
- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- backend/.gitignore
- backend/pom.xml
- fly.toml
- my-app/package.json
- my-app/src/reportWebVitals.js
🎉 Add ci + ci/cd GH action workflows
We'll run ci each time someone opens a pull request, and double check our whole application builds, tests are green, & is formatted correctly
We'll run ci/cd each time someone pushes to main. We'll do all of the above, + package the entire application into a container, & let [fly.io](https://fly.io/) run that container. 
Why fly? Can't have a runaway credit card bill and they're most straightforward way to run containers - that I'm aware of : )
Before you consider merging this PR, you'll have to set this repo's `FLY_API_TOKEN`. Dm me ur email, i'll add u as an admin to the org, and then u can fetch the token with `flyctl auth token`
> Add ci + ci/cd GH action workflows

- my-app/src/components/CreateAccountPage/CreateAccountPage.jsx
Does not have anything to do with profile modal, that is no longer needed and I closed the issue. I just imporved the code for validating creation of a user
> Improved user creation

- my-app/src/components/CourseSwapPage/CourseSwapPage.css
- my-app/src/components/CourseSwapPage/CourseSwapPage.jsx
- my-app/src/components/CourseSwapPage/Tab.jsx
- my-app/src/components/FAQPage/FAQPage.css
- my-app/src/components/FAQPage/FAQPage.jsx
- my-app/src/components/MainTheme.css
I made it so each course swap offer also has a course request tab that the user can switch to and from. 
Tab File: I added a Tab file to accomplish this, and this file could be moved higher in the components folder as it is very customizable and could be used on the other pages if wanted. It uses react.createContext, which is meant to be used sparingly, so if someone can recreate the Tabs to have the same functions while still being very customizable, please do so, and thank you.
Side-Note for CSS files: Please do not write CSS for components like "nav { stuff }" in your CSS files, as it will affect all other pages. Also, make sure when doing className="stuff" in the jsx files that the class name is not used in another file. If it is, then differentiate the class name of your components …
> Managed to add tabs to the content in course swap page

- my-app/src/components/CreateAccountPage/CreateAccountPage.css
- my-app/src/components/CreateAccountPage/CreateAccountPage.jsx
- my-app/src/firebase.js
Authentication isnt broken anymore
> Authentication

- my-app/package.json
> add firebase to package.json dependencies

- backend/scripts/run_backend.sh
- backend/src/main/java/com/uga/backend/entity/Textbook.java
- backend/src/main/java/com/uga/backend/handler/TextbookHandler.java
- backend/src/main/java/com/uga/backend/service/TextbookService.java
- my-app/src/components/CreateAccountPage/CreateAccountPage.jsx
- my-app/src/firebase.js
> Email verification now works

- backend/pom.xml
- backend/src/main/java/com/uga/backend/CorsGlobalConfiguration.java
- backend/src/main/java/com/uga/backend/entity/Textbook.java
- backend/src/main/java/com/uga/backend/firebase/FirebaseIntialization.java
- backend/src/main/java/com/uga/backend/handler/TextbookHandler.java
- backend/src/main/java/com/uga/backend/repo/TextbookRepository.java
- backend/src/main/java/com/uga/backend/router/TextbookRouter.java
Added some paramters to textbook as requested by frontend peeps
> Some changes to Textbook backend schema

- my-app/src/components/CourseSwapPage/CourseSwapPage.jsx
- my-app/src/components/MainTheme.css
There was an error with a previous PR that reset some files with several commits. Just pull this to restore the changes made.
> Fixed code deletion from broken merge

- my-app/src/App.css
- my-app/src/components/CourseSwapPage/CourseSwapPage.css
- my-app/src/components/CourseSwapPage/CourseSwapPage.jsx
- my-app/src/components/FAQPage/FAQPage.css
- my-app/src/components/HomeNavbar/HomeNavbar.css
- my-app/src/components/HousingPage/HousingPage.css
- my-app/src/components/MainTheme.css
- my-app/src/components/TextBookPage/TextBook.css
- my-app/src/components/TicketPage/TicketPage.css
- my-app/src/components/TicketPage/TicketPage.jsx
- my-app/src/components/TrendingItems/TrendingItems.css
- my-app/src/components/TrendingItems/TrendingItems.jsx
Using "position: fixed;" I made it so both the sidebar and topbar are not moving when you scroll. I needed to slightly modify the CSS of all the pages to account for the fixed position of the top bar. I also ran prettier so some .jsx got modified.
BUGS: 
- There is still an issue with CSS components from different files getting inherited due to having the same class names.
- The sidebar on the homepage still moves due to how the CSS for that page was made.
> Made sidebar and Topbar unscrollable mostly

- backend/src/main/java/com/uga/backend/handler/TextbookHandler.java
- backend/src/main/java/com/uga/backend/router/TextbookRouter.java
- backend/src/main/java/com/uga/backend/service/TextbookService.java
Made the basics for the tickets backend
> Made the tickets backend

- backend/src/main/java/com/uga/backend/entity/Course.java
- backend/src/main/java/com/uga/backend/entity/CourseSwap.java
- my-app/src/App.js
- my-app/src/components/CourseSwapPage/CourseSwapPage.css
- my-app/src/components/CourseSwapPage/CourseSwapPage.jsx
- my-app/src/components/CourseSwapPage/CourseSwapPagePersonal.jsx
- my-app/src/components/CourseSwapPage/CourseSwapPageSaved.jsx
Added personal and saved pages for courseSwap page. Also tried doing some backend on courseSwap
> Course swap

- my-app/src/App.js
- my-app/src/components/HomeNavbar/HomeNavbar.css
- my-app/src/components/HomeNavbar/HomeNavbar.jsx
- my-app/src/components/MainTheme.css
- my-app/src/components/TutorPage/TutorPage.css
- my-app/src/components/TutorPage/TutorPage.jsx
- package-lock.json
I also changed maintheme.css to help with the sidebar problem.
> added TutorPage

- backend/pom.xml
- backend/src/main/java/com/uga/backend/BackendApplication.java
- backend/src/main/java/com/uga/backend/controller/CourseSwapController.java
- backend/src/main/java/com/uga/backend/controller/ParkingPassController.java
- backend/src/main/java/com/uga/backend/controller/TextbookController.java
- backend/src/main/java/com/uga/backend/controller/TicketController.java
- backend/src/main/java/com/uga/backend/entity/Course.java
- backend/src/main/java/com/uga/backend/entity/CourseSwap.java
- backend/src/main/java/com/uga/backend/entity/ParkingPass.java
- backend/src/main/java/com/uga/backend/entity/Textbook.java
- backend/src/main/java/com/uga/backend/entity/Ticket.java
- backend/src/main/java/com/uga/backend/firebase/FirebaseIntialization.java
- backend/src/main/java/com/uga/backend/handler/TextbookHandler.java
- backend/src/main/java/com/uga/backend/handler/TicketHandler.java
- backend/src/main/java/com/uga/backend/repository/ParkingPassRepository.java
- backend/src/main/java/com/uga/backend/repository/TextbookRepository.java
- backend/src/main/java/com/uga/backend/repository/TicketRepository.java
- backend/src/main/resources/application.properties
Rewrote the backend to use FirestoreReactiveRepositories instead of services, handlers, and routers
> New backend

- my-app/src/components/TicketPage/TicketPage.jsx
Fixed the filtering on TicketPage
> Fixed the filtering on TicketPage
